INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (63089044064, 'Camilla A. Pereira', 'Belém', 'PA');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (62870064802, 'José Figueiredo', 'Contagem', 'MG');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (70850304000123, 'Mix Açaí', 'Belo Horizonte', 'MG');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (27241469720, 'Jucinalva André', 'Palmas', 'TO');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (17795961207, 'Phil Keaggy', 'Brasília', 'DF');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (25241684174, 'Alex Azevedo', 'Bom Jesus do Galho', 'MG');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (73051947008, 'Cesino Vieira', 'Jundiaí', 'RJ');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (99053055568, 'Ruth Alvez', 'Campinas', 'SP');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (67275632845, 'Luciana Ribeiro', 'Monte Verde', 'MG');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (76000611200, 'Jorge Rabelo', 'Goiânia', 'GO');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (93476989976, 'Ana Carolina', 'Maringá', 'MT');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (36376825087, 'Alex Golveia', 'Itaoca', 'ES');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (44701712000103, 'Rei do Kibe', 'Belo Horizonte', 'MG');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (94866840145, 'Luiza Serrano', 'Manaus', 'AM');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (99402364684, 'Raul Teixeira', 'Curitiba', 'PR');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (22581250000103, 'MK Music', 'Rio de Janeiro', 'RJ');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (00273311727, 'Márcio Freire', 'Bonito', 'GO');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (49792551166, 'Rodolfo Silva', 'Teixeira de Freitas', 'BA');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (84552328387, 'Fernando Luiz', 'Maceió', 'AL');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (72101958902, 'Hugo Regis', 'Oiapoque', 'AP');
INSERT INTO `wk_teste_pedido_venda`.`cliente` (`cod_cliente`, `nome_cliente`, `cidade_cliente`, `uf_cliente`) VALUES (61197274340, 'Emerson Santos', 'Pelotas', 'RS');
COMMIT;